/// <reference path="../component/media/media.controller.ts"/>
/// <reference path="../component/nav/nav.controller.ts"/>
/// <reference path="../component/tab/tab.controller.ts"/>
/// <reference path="../object/file/file.controller.ts"/>
/// <reference path="../object/mark/mark.controller.ts"/>
/// <reference path="../object/modal/modal.controller.ts"/>
/// <reference path="../object/options/options.controller.ts"/>
/// <reference path="../object/steps/steps.controller.ts"/>
/// <reference path="../object/toast/toast.controller.ts"/>

window["FileController"] = new FileController();    
window["MarkController"] = new MarkController();
window["MediaController"] = new MediaController();
window["ModalController"] = new ModalController();
window["NavController"] = new NavController();
window["OptionsController"] = new OptionsController();
window["StepsController"] = new StepsController();
window["TabController"] = new TabController();
window["ToastController"] = new ToastController();