/// <reference path="../component/media/media.controller.ts"/>
/// <reference path="../component/nav/nav.controller.ts"/>
/// <reference path="../component/tab/tab.controller.ts"/>
/// <reference path="../object/dialog/dialog.controller.ts"/>
/// <reference path="../object/file/file.controller.ts"/>
/// <reference path="../object/loading/loading.controller.ts"/>
/// <reference path="../object/mark/mark.controller.ts"/>
/// <reference path="../object/modal/modal.controller.ts"/>
/// <reference path="../object/options/options.controller.ts"/>
/// <reference path="../object/processing/processing.controller.ts"/>
/// <reference path="../object/steps/steps.controller.ts"/>
/// <reference path="../object/toast/toast.controller.ts"/>
/// <reference path="../object/toast_slim/toastslim.controller.ts"/>

window["DialogController"] = new DialogController();    
window["FileController"] = new FileController();    
window["MarkController"] = new MarkController();
window["LoadingController"] = new LoadingController();
window["MediaController"] = new MediaController();
window["ModalController"] = new ModalController();
window["NavController"] = new NavController();
window["OptionsController"] = new OptionsController();
window["ProcessingController"] = new ProcessingController();
window["StepsController"] = new StepsController();
window["TabController"] = new TabController();
window["ToastController"] = new ToastController();
window["ToastSlimController"] = new ToastSlimController();